# Generated by Django 3.2.5 on 2021-09-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filter',
            name='unique filter constraint',
        ),
        migrations.AddField(
            model_name='filter',
            name='type',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='filter',
            constraint=models.UniqueConstraint(fields=('name', 'value', 'type'), name='unique filter constraint'),
        ),
    ]
