# Generated by Django 3.2.6 on 2021-08-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='last_crawled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
