# Generated by Django 3.2.5 on 2022-12-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210909_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlink', models.CharField(max_length=512)),
                ('authority', models.IntegerField(blank=True, default=0, null=True)),
                ('crawled_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expressions', models.JSONField()),
                ('scope', models.CharField(default='Universal', max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'scope'), name='unique tag constraint'),
        ),
        migrations.AddField(
            model_name='backlink',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddConstraint(
            model_name='backlink',
            constraint=models.UniqueConstraint(fields=('property', 'backlink'), name='unique property backlink constraint'),
        ),
    ]
