# Generated by Django 3.2.5 on 2023-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20221208_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='scrape_priority',
            new_name='priority_coverage',
        ),
        migrations.AddField(
            model_name='property',
            name='priority_backlink',
            field=models.CharField(default='low', max_length=100),
        ),
    ]
