# Generated by Django 3.2.5 on 2023-06-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20230220_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='last_scraped',
            new_name='last_scraped_backlink',
        ),
        migrations.AddField(
            model_name='property',
            name='last_scraped_coverage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_scraped_musability',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='priority_musability',
            field=models.CharField(default='low', max_length=100),
        ),
    ]
