# Generated by Django 3.2.6 on 2021-08-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_last_scrapeed_property_last_scraped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='urls_count',
            new_name='num_urls',
        ),
    ]
