# Generated by Django 3.2.6 on 2021-08-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_urls_count_log_num_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='c_status',
            field=models.CharField(blank=True, default='Not listed', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='c_type',
            field=models.CharField(blank=True, default='Not listed', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='mu_type',
            field=models.CharField(blank=True, default='Not listed', max_length=255, null=True),
        ),
    ]
