# Generated by Django 3.2.5 on 2023-07-17 21:18
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20230615_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at',models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
