# Generated by Django 3.2.6 on 2021-08-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20210819_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='scrape_priority',
            field=models.CharField(default='low', max_length=100),
        ),
    ]
