# Generated by Django 3.2.6 on 2021-08-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_log_scrape_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
