# Generated by Django 3.2.5 on 2023-08-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlink',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
