# Generated by Django 3.2.5 on 2023-08-03 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_backlink_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklinkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.backlink')),
            ],
        ),
    ]
