# Generated by Django 3.2.6 on 2021-08-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20210827_1349'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filter',
            constraint=models.UniqueConstraint(fields=('name', 'value'), name='unique filter constraint'),
        ),
    ]
